#!/bin/bash

sudo cp pacman.conf /etc/
sudo pacman -Syu

echo ""
read -r -p "Do you want to install Minecraft Launcher? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sudo pacman -S --needed --noconfirm jre-openjdk
    wget -q -nc --show-progress https://launcher.mojang.com/download/Minecraft.tar.gz
    tar -xf Minecraft.tar.gz
    sudo cp minecraft-launcher/minecraft-launcher /usr/bin/
    sudo wget -q -nc https://launcher.mojang.com/download/minecraft-launcher.svg -P /usr/share/icons/hicolor/symbolic/apps/
    echo -e "[Desktop Entry]\nType=Application\nVersion=1.0\nName=Minecraft Launcher\nComment=Official Minecraft Launcher\nExec=minecraft-launcher\nIcon=minecraft-launcher\nTerminal=false\nCategories=Game;Application;\nStartupWMClass=minecraft-launcher" | sudo tee /usr/share/applications/minecraft-launcher.desktop > /dev/null
fi

echo ""
read -r -p "Do you want to install Lutris(Without Wine)? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sudo pacman -S --needed --noconfirm lutris gamemode gvfs innoextract lib32-gamemode lib32-vkd3d lib32-vulkan-icd-loader python-protobuf vkd3d vulkan-icd-loader vulkan-tools xorg-xgamma
fi

echo ""
read -r -p "Do you want to install Wine(+winetricks)? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sudo pacman -S --needed --noconfirm wine winetricks $(pacman -Si wine | sed -n '/^Optional Deps/,/^Conflicts With/p' | sed '$d' | sed 's/^Optional Deps   ://g' | sed 's/^\s*//g')
    sudo systemctl restart systemd-binfmt
    wine reg.exe add HKCU\\Software\\Wine\\Drivers /v Graphics /d x11,wayland
fi

echo ""
read -r -p "Do you want to install Mangohud? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sudo pacman -S --needed --noconfirm mangohud lib32-mangohud gamescope glfw
fi

echo ""
read -r -p "Do you want to install Steam? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sudo pacman -S --needed --noconfirm steam
fi
